version: '2'

services:
  deployr:
    build: deployr
    volumes:
      - projects:/miracle/projects
      - packrat:/miracle/packrat
    environment:
  #### Variables below are used in deployr/addUser.py line 21
      DEPLOYR_USER: miracle

  radiant:
    build: radiant
    volumes:
      - projects:/miracle/projects
      - packrat:/miracle/packrat
    depends_on:
      - db
  #### Change radiant-mod:/srv/shiny-server/base/tools/data/manage_ui.R line 457
  #### Only need a read_only user for the `miracle_metadata` database

  db:
    image: sameersbn/postgresql:9.4-21
    environment:
      DB_USER: miracle
      DB_PASS: changeme_db
      DB_NAME: 'miracle_data,miracle_metadata'

  django:
    build: 
        context: ./django
        args:
            reqfile: "local.txt"
    volumes:
      - .:/code
      - projects:/miracle/projects
      - packrat:/miracle/packrat
      - static:/miracle/static
      - archives:/miracle/archives
      - socket:/miracle/socket
      - logs:/miracle/logs
    environment:
  #### Change settings/local.py file for DEPLOYR_PASS 
  #### Default MIRACLE_USER is a Django admin user
      DB_USER: miracle
      DB_HOST: db
      DB_PORT: 5432
      DEPLOYR_USER: miracle 
      DEPLOYR_HOST: deployr
      DEPLOYR_URL: 'http://deployr:8000/deployr'
      MIRACLE_USER:  admin
      MIRACLE_EMAIL: "miracle-admin@comses.net"
      RADIANT_URL: '/radiant/'
    depends_on:
      - db

  nginx:
    build: 
        context: ./nginx
        args:
            siteconf: "local.conf"
    volumes:
      - socket:/miracle/socket
      - static:/miracle/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
   
volumes:
  projects:
    driver: local
  packrat:
    driver: local
  static: 
    driver: local
  archives: 
    driver: local
  logs:
    driver: local
  socket:
    driver: local
