---
deployr_data:
  build: deployr
  volumes:
    - /home/miracle/deployr/7.4.1/deployr/database
  command: echo deployr_data

deployr:
  build: deployr
  volumes_from:
    - django_filesystem
    - deployr_data
  ports: 
    - "7400:7400"

radiant:
  build: radiant
  volumes_from:
    - django_filesystem
  ports: 
    - "3838:3838"

db:
  image: sameersbn/postgresql:9.4-3
  ports: 
    - "5432:15432"
  environment:
    DB_USER: miracle
    DB_PASS: CHANGEME
    DB_NAME: 'miracle_data,miracle_metadata'
    PSQL_TRUST_LOCALNET: 'true'

django_filesystem:
  build: django
  volumes:
    - ./miracle:/miracle

django:
  build: django
  volumes:
    - ./django:/code
    - ./test_archives:/tmp
  volumes_from:
    - django_filesystem
  command: python /code/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  links:
    - db
